name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - prod  # This workflow triggers when there is a push to the main branch
  workflow_dispatch:  # Allows manually triggering the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/kms-service:latest
            ghcr.io/${{ github.repository }}/kms-service:${{ github.sha }}

      - name: Verify the image is in the registry
        run: |
          echo "Listing images in the GHCR repository..."
          curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} https://ghcr.io/v2/${{ github.repository }}/kms-service/tags/list
